<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNvpKw0a\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNvpKw0a/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNvpKw0a.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNvpKw0a\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNvpKw0a\App_KernelDevDebugContainer([
    'container.build_hash' => 'NvpKw0a',
    'container.build_id' => 'c41288cb',
    'container.build_time' => 1705320370,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNvpKw0a');
