<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSqVEz1T\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSqVEz1T/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSqVEz1T.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSqVEz1T\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSqVEz1T\App_KernelDevDebugContainer([
    'container.build_hash' => 'SqVEz1T',
    'container.build_id' => '9289a319',
    'container.build_time' => 1704921487,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSqVEz1T');
