<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXlejPe0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXlejPe0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXlejPe0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXlejPe0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXlejPe0\App_KernelDevDebugContainer([
    'container.build_hash' => 'XlejPe0',
    'container.build_id' => '6091aa23',
    'container.build_time' => 1705005831,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXlejPe0');
